---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 15:04
---
local actions = {
    finished = 0,
    process = 1,
    up = 2,
	down = 3,
	idle = 4,
	loading = 5,
	unloading = 6,
	processing = 7,
	operate = 8
	
}

return actions