---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 10:14
---

local conf = {
    {id = "2020140180297"},
    {id = "wr1", ip = "127.0.0.1"},
    {id = "wr2", ip = "127.0.0.1"},
    {id = "wr3", ip = "127.0.0.1"},
    {id = "wr4", ip = "127.0.0.1"},
    {id = "b1", ip = "127.0.0.1"},
    {id = "b2", ip = "127.0.0.1"},
	{id = "robot1", ip = "127.0.0.1"},
	{id = "robot2", ip = "127.0.0.1"},
	{id = "robot3", ip = "127.0.0.1"},
	{id = "robot4", ip = "127.0.0.1"},
	{id = "fqc", ip = "127.0.0.1"},
	{id = "conveyer1", ip = "127.0.0.1"},
	{id = "conveyer2", ip = "127.0.0.1"}
}

return conf

