---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 6:11
--- è´¨æ£€æœºå™¨äºº

local fqc = {
    debug = true,
    stateTimer = {}
}

--- run ÔËĞĞ×´Ì¬»ú
function fqc:run()
    local time = require("timer")
  local client = {
        id = conf.id or "fqc",
        ip = conf.ip or "127.0.0.1"
}
    setmetatable(client, { __index = self })
    client:subscribe()
    timer.afterFunc(3000, function()
        client:changeState("s_fqc_connect")
    end)  -- ÔÚ´Ë´¦Ìí¼ÓÒ»¸ö±ÕºÏµÄÀ¨ºÅ
    return client
end

--- changeState ¸Ä±ä×´Ì¬»úµ±Ç°×´Ì¬
function fqc:changeState(name, ...)
    log(name)
    for _, timerId in pairs(self.stateTimer) do
        time.removeTimer(timerId)
    end
    if self.state ~= nil and self.state.exit ~= nil then
        self.state:exit(self)
    end
    self.state = require(name)
    self.state:run(self, ...)
end

--- subscribe ¶©ÔÄÏûÏ¢
function fqc:subscribe()
    mqtt:Subscribe(self.id, function(data)
        if self.state ~= nil and self.state.onEvent ~= nil then
            self.state:onEvent(self, data)
        end
    end)
end

--- publish ·¢²¼ÏûÏ¢
function fqc:publish(data)
    mqtt:Publish(self.id, data)
end

--- connected ÒÑÁ¬½ÓÔË¶¯¿ØÖÆÆ÷
function fqc:connected()
    return self.handle ~= nil
end

--- connected ÒÑÁ¬½ÓÔË¶¯¿ØÖÆÆ÷
function fqc:createTimer(key, interval, callback)
    local id = time.createTimer(interval, callback)
    self.stateTimer[key] = id
end

--- removeTimer É¾³ı×´Ì¬´´½¨µÄ¶¨Ê±Æ÷
---   key ¶¨Ê±Æ÷Ãû³Æ(Èç¹ûÎª¿ÕÔòÉ¾³ıÈ«²¿)
function fqc:removeTimer(key)
    if key==nil then
        for _, timerId in pairs(self.stateTimer) do
            time.removeTimer(timerId)
        end
        return
    end
    local id = self.stateTimer[key]
    if id~=nil then
        time.removeTimer(id)
    end
end

return fqc
