---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 5:52
--- Sichan University IE 516 智能制造产线控制系统
---
timer = require("timer")
mqtt = require("mqtt")
conf = require("conf")
actions = require("actions")

machines = {
    comment = "machine"
}

function main()
    conf = require("conf")
	print( "1")
	for _, c in ipairs(conf) do
        machines[c.id] = require("writer"):run(c)
        print(machines[c.id]:connected())
        --local w = require("writer"):run(c)
        --print(w:connected())
    end
    require("b1"):run(conf)
    timer.sleep(5000)
    require("b2"):run(conf)
    timer.sleep(5000)
    require("robot1"):run(conf)
    timer.sleep(5000)
	require("robot2"):run(conf)
    timer.sleep(5000)
	require("robot3"):run(conf)
    timer.sleep(5000)
	require("robot4"):run(conf)
    timer.sleep(5000)
	require("fqc"):run(conf)
    timer.sleep(5000)
	require("conveyer1"):run(conf)
    timer.sleep(5000)
	require("conveyer2"):run(conf)
    timer.sleep(5000)
    --publish(conf.id, {
    --    id = "wr1",
    --    action = actions.process,
    --    nc = "123.nc",
    --})
end

function publish(id, data)
    mqtt:Publish(id, data)
end

function log(fmt, ...)
    print(fmt, ...)
end

--- connected 宸茶繛鎺ヨ繍鍔ㄦ帶鍒跺櫒
function failed(err)
    if err == nil then
        return false
    end
    print(err)
    return true
end

main()
