---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/5/22 10:58
---

local mqtt = {}

function mqtt:Subscribe(channel, callback)
    --self[channel] = self[channel]
end

return mqtt
