---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 14:58
--- 正在加工

local s_fqc_process = {
    comment = "拍照状态"
}

function s_fqc_process:run(fqc, ...)
	time.sleep(3000)
	--fqc:publish(data)
	fqc:changeState("s_fqc_idle")
    --[[local args = { ... }
    if #args < 1 then
        w:changeState("s_idle")
        return
    end
    if failed(zmc.run(w.handle, args[1])) then
        time.sleep(3000)
        print("sleep 3......")
    end
    w:changeState("s_idle")--]]
end

--- publish 发布消息
function fqc:publish(data)
    mqtt:Publish(self.id, data)
end

function s_fqc_process:exit(fqc)
end

function s_fqc_process:onEvent(fqc, data)
    --print("s_process.onEvent", fqc.id, data.a, data.b, data.c)

end

return s_fqc_process
