---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_homing = {
    comment = "回零"
}

function s_homing:run(w, ...)
    print("s_homing:run")
    timer:sleep(3000)
    w:changeState("s_idle")
    --zmc.cancelOnline(w.handle)
    --zmc.stop(w.handle)
    ----if failed(zmc.moveAbs(w.handle, 100, 200, 300)) then
    ----    w:changeState("s_connect")
    ----    return
    ----end
    --if failed(zmc.homing(w.handle)) then
    --    time.sleep(1000)
    --    w:changeState("s_connect")
    --    return
    --end
    --w:changeState("s_idle")
end

function s_homing:exit(w)
end

function s_homing:onEvent(w, data)
    --print("s_homing.onEvent", w.id, unpack(data))
end

return s_homing