---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:46
--- è¿æ¥çŠ¶æ€

local s_r1_connect = {
    comment = "»úÆ÷ÈË1ÍøÂçÁ¬½Ó×´Ì¬"
}

function s_r1_connect:run(r1, ...)
	print( "1")
    timer.sleep(3000)
    r1:changeState("s_r1_idle")
end

function s_r1_connect:exit(r1)
    -- ÔÚÍË³ö×´Ì¬Ê±Ö´ĞĞµÄÂß¼­
end

function s_r1_connect:connect(r1)
    -- Á¬½ÓÂß¼­£¬¸ù¾İÊµ¼ÊÇé¿ö½øĞĞÊµÏÖ
    -- Èç¹ûÁ¬½Ó³É¹¦£¬·µ»Ø true£»·ñÔò·µ»Ø false
    -- ¿ÉÒÔÊ¹ÓÃ r1.ip ºÍ r1.id ½øĞĞÁ¬½Ó²Ù×÷
end

function s_r1_connect:onEvent(r1, data)
    -- ÔÚ½ÓÊÕµ½ÊÂ¼şÊ±µÄÂß¼­´¦Àí
end

return s_r1_connect

