---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_r1_idle = {
    comment = "空闲状态"
}

function s_r1_idle:run(r1)
    -- 创建定时器
    --w:createTimer("idle.test", 6000, function()
    --    print("idle.test timeout")
    --end)
    --- just for demo
    --time.afterFunc(5, function()
    --    w:publish({
    --        id = w.id,
    --        action = actions.process,
    --        nc = "123.nc",
    --    })
    --end)
end

function s_r1_idle:exit(r1)
end

function s_r1_idle:onEvent(r1, data)
    --[[if data.action == actions.process and data.nc ~= nil and data.id == w.id then
        r1:changeState("s_process", data.nc)	
    end--]]
	if data.action == actions.loading and data.id == r1.id then
        r1:changeState("s_r1_process")
	end
end

return s_r1_idle