---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_r1_homing = {
    comment = "回零"
}

function s_r1_homing:run(r1, ...)
	timer.sleep(1000)
	r1:changeState("s_r1_idle")
   --[[ zmc.cancelOnline(w.handle)
    zmc.stop(w.handle)
    --if failed(zmc.moveAbs(w.handle, 100, 200, 300)) then
    --    w:changeState("s_connect")
    --    return
    --end
    if failed(zmc.homing(w.handle)) then
        time.sleep(1000)
        w:changeState("s_connect")
        return
    end
    w:changeState("s_idle")--]]
end

function s_r1_homing:exit(r1)
end

function s_r1_homing:onEvent(r1, data)
    --print("s_homing.onEvent", w.id, unpack(data))
end

return s_r1_homing