---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 14:58
--- 正在加工

local s_r2_loading = {
    comment = "加工状态"
}

function s_r2_loading:run(r2, ...)
	time.sleep(3000)
    print("sleep 3......")
	r2:publish({
            id = r2.id,
            action = actions.loading,
        })
	r2:changeState("s_r2_idle")
end

function s_r2_loading:exit(r2)
end

function s_r2_loading:onEvent(r2, data)
    --print("s_r2_loading.onEvent", r2.id, data.a, data.b, data.c)

end

return s_r2_loading