---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:46
--- 连接状态

local s_r2_connect = {
    comment = "与zmc建立网络连接"
}

function s_r2_connect:run(r2, ...)
	timer.sleep(3000)
	r2:changeState("s_r2_idle")
    --r2:createTimer("s_r2_connect.test", 6000, function()
    --    print("s_r2_connect.test timeout")
    --end)
    --[[while (self:connect(r2) ~= true)
    do
        time.sleep(3000)
    end
    r2:changeState("s_r2_homing")--]]
end

function s_r2_connect:exit(r2)
    --print("s_connect:exit")
end

function s_r2_connect:connect(r2)
	return true
    --[[if r2.handle ~= nil then
        zmc.close(r2.handle)
        r2.handle = nil
        return false
    end
    r2.handle, err = zmc.connect(r2.ip)
    if failed(err) then
        log(self, err)
        return false
    end
    log("连接到运动控制器", r2.ip)
    return r2.handle ~= nil--]]
end

function s_r2_connect:onEvent(r2, data)
    --print("s_r2_connect.onEvent", r2.id, data.a, data.b, data.c)
end

return s_r2_connect
