---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:46
--- 连接状态

local s_r3_connect = {
    comment = "与zmc建立网络连接"
}

function s_r3_connect:run(r3, ...)
	timer.sleep(3000)
	r3:changeState("s_r3_idle")
    --r3:createTimer("s_r3_connect.test", 6000, function()
    --    print("s_r3_connect.test timeout")
    --end)
    --[[while (self:connect(r3) ~= true)
    do
        timer.sleep(3000)
    end
    r3:changeState("s_homing")--]]
end

function s_r3_connect:exit(r3)
    --print("s_connect:exit")
end

function s_r3_connect:connect(r3)
	return true
    --[[if w.handle ~= nil then
        zmc.close(w.handle)
        w.handle = nil
        return false
    end
    w.handle, err = zmc.connect(w.ip)
    if failed(err) then
        log(self, err)
        return false
    end
    log("连接到运动控制器", w.ip)
    return w.handle ~= nil--]]
end

function s_r3_connect:onEvent(r3, data)
    --print("s_connect.onEvent", r3.id, data.a, data.b, data.c)
end

return s_r3_connect
