---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_r3_idle = {
    comment = "空闲状态"
}

function s_r3_idle:run(r3)
    -- 创建定时器
    --r3:createTimer("idle.test", 6000, function()
    --    print("idle.test timeout")
    --end)
    --- just for demo
    --time.afterFunc(5, function()
    --    r3:publish({
    --        id = r3.id,
    --        action = actions.process,
    --        nc = "123.nc",
    --    })
    --end)
end

function s_r3_idle:exit(r3)
end

function s_r3_idle:onEvent(r3, data)
    if data.action == actions.loading and data.id == r3.id then
        r3:changeState("s_r3_loading")
	end
	if data.action == actions.unloading and data.id == r3.id then
        r3:changeState("s_r3_unloading")
    end
end

return s_r3_idle