---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 14:58
--- 正在加工

local s_r3_unloading = {
    comment = "加工状态"
}

function s_r3_unloading:run(r3, ...)
	time.sleep(3000)
    print("sleep 3......")
	r3:publish({
            id = r3.id,
            action = actions.unloading,
        })
	r3:changeState("s_r3_idle")
end

function s_r3_unloading:exit(r3)
end

function s_r3_unloading:onEvent(r3, data)
    --print("s_process.onEvent", r3.id, data.a, data.b, data.c)

end

return s_r3_unloading