---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_r4_idle = {
    comment = "空闲状态"
}

function s_r4_idle:run(r4)
    -- 创建定时器
    --r4:createTimer("idle.test", 6000, function()
    --    print("idle.test timeout")
    --end)
    --- just for demo
    --time.afterFunc(5, function()
    --    r4:publish({
    --        id = r4.id,
    --        action = actions.unloading,
    --        nc = "123.nc",
    --    })
    --end)
end

function s_r4_idle:exit(r4)
end

function s_r4_idle:onEvent(r4, data)
	if data.action == actions.reset and data.id == r4.id then
        r4:changeState("s_r4_reset")
    end
    if data.action == actions.unloading and data.id == r4.id then
        r4:changeState("s_r4_unloading")
    end
end

return s_r4_idle