---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 9:50
---
local s_r4_homing = {
    comment = "回零"
}

function s_r4_homing:run(r4, ...)
	timer.sleep(1000)
	r4:changeState("s_r4_idle")
    --zmc.cancelOnline(r4.handle)
   --[[ zmc.stop(r4.handle)
    if failed(zmc.moveAbs(r4.handle, 100, 200, 300)) then
        r4:changeState("s_r4_connect")
        return
    end
	time.sleep(1000)
    if failed(zmc.homing(r4.handle)) then--]]
        --time.sleep(1000)
       -- r4:changeState("s_r4_connect")
       -- return
    --end
    --r4:changeState("s_r4_idle")
end

function s_r4_homing:exit(r4)
end

function s_r4_homing:onEvent(r4, data)
    --print("s_r4_homing.onEvent", r4.id, unpack(data))
end

return s_r4_homing
