---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/5/22 10:47
---
local timer = {}

function timer.sleep(d)
  -- 添加 sleep 函数的具体实现
end

function timer.afterFunc(d, callback)
  timer.sleep(d)
  if type(callback) == "function" then
    callback()
  end
end

return timer
