---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by gepeng.
--- DateTime: 2023/4/25 17:25
--- zmc 运动控制器api

zmc = {}

function zmc.connect(ip) end
function zmc.cancelOnline(handle) end --- 取消当前正在执行的命令
function zmc.close(handle) end
function zmc.pause(handle) end
function zmc.stop(handle) end --- ZMC_Stop 暂停继续运行程序
function zmc.resume(handle) end
function zmc.homing(handle) end
function zmc.moveAbs(handle, x,y,z) end
function zmc.run(handle, nc) end
return zmc